#!/usr/bin/env bash
# GENERATED by scripts/export-hooks-to-copilot.js — do not edit by hand.
# Copilot hook wrapper for hooks/ralph-loop.js (v3.5 Copilot port).
ROOT="${COPILOT_PLUGIN_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
COPILOT=1 exec node "$ROOT/hooks/ralph-loop.js"
