#!/usr/bin/env bash
# GENERATED by scripts/export-hooks-to-copilot.js — do not edit by hand.
# Copilot hook wrapper for hooks/scope-directory.js (v3.5 Copilot port).
HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
COPILOT=1 exec node "$HERE/../../../hooks/scope-directory.js"
