#!/usr/bin/env bash
# GENERATED by scripts/export-hooks-to-copilot.js — do not edit by hand.
# Copilot hook wrapper for hooks/token-advisor.js (v3.5 Copilot port).
cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)" || exit 0
COPILOT=1 exec node "hooks/token-advisor.js"
